swiftmailer:
    transport:            smtp
    username:             a.kavera@outlook.fr
    password:             Commercy1411
    host:                 localhost
    port:                 587
    encryption:           ~
    auth_mode:            login
    spool:
        type:                 file
        path:                 '%kernel.cache_dir%/swiftmailer/spool'
    sender_address:       ~
    antiflood:
        threshold:            99
        sleep:                0
    delivery_addresses:   []
    disable_delivery:     ~
    logging:              '%kernel.debug%'